library(shiny)
library(shinythemes)
library(shinyBS)
library(jsonlite)
library(markdown)

# features to add
# frequency plot?
# Explanatory text
# better valence mens

options(shiny.maxRequestSize = 30*1024^2)

pops <- fromJSON("data/popovers.json")

shinyUI(fluidPage(
  
  theme = shinytheme("flatly"),
  br(),
  titlePanel("Name embeddings"),
  helpText("Explore the semantic associations of English names!"),
  
  fluidRow(
    column(3,
           wellPanel(
              helpText(h3("Names")),
              helpText("Enter up to 5 names to explore:"),
              
              popify(textInput("target_name1", label = "", value = "Emma"),
                     title = NULL,
                     content = HTML(sprintf("<small>%s</small>", pops$words)),
                placement = "right"),
              popify(textInput("target_name2", label = ""),
                title = NULL,
                content = HTML(sprintf("<small>%s</small>", pops$words)),
                placement = "right"),
              popify(textInput("target_name3", label = ""),
                title = NULL,
                content = HTML(sprintf("<small>%s</small>", pops$words)),
                placement = "right"),
              popify(textInput("target_name4", label = ""),
                title = NULL,
                content = HTML(sprintf("<small>%s</small>", pops$words)),
                placement = "right"),
              popify(textInput("target_name5", label = ""),
                title = NULL,
                content = HTML(sprintf("<small>%s</small>", pops$words)),
                placement = "right"))
    ),
    
    column(9,
           tags$style(type = "text/css",
                      ".shiny-output-error { visibility: hidden; }",
                      ".shiny-output-error:before { visibility: hidden; }"),
           tabsetPanel(
             tabPanel("Name Semantic Space",
                      br(),
                      HTML("The plot below shows the semantics coordinates for names based on a word embedding model trained on English."),
                      
                      plotlyOutput("name_plot", height = "1200px"),
                        br(),
                        downloadButton("download_plot", "Download Plot",
                                       class = "btn-default btn-xs"),
                        br(),br()),
             tabPanel("Most Associated Traits",
                      br(),
                      HTML("The top 25 traits associated with each name based on distance in a word embedding model trained on English."),
                                            br(), br(),
                      fluidRow(
                         column(width = 10, tableOutput("tab"))
                      )),
              tabPanel("Mean Trait Valence",
                       br(),
                       HTML("The plot below shows the mean valence (negative vs. positive) of the N traits most associated with each name. Ranges correspond to bootstrapped 95% confidence intervals."),
                       
                       br(),
                       br(),
                      sliderInput("n_traits", "N traits:",
                                  min = 0, max = 100 ,
                                  value = 25),
                      br(),
                      br(),
                      plotOutput("name_valence_plot", height = "1000px"),
                      br(),br()),
             tabPanel("Details",
                      br(),
                      HTML("The app includes the top 2000 male and 2000 female baby names based on 2017 Social Security Administration data (Wickham, 2019). The embeddings are derived from a fastText model trained on English Wikipedia (Bojanowski, 2016); 2D projection of coordinates were calculated using the umap algorithm (McInnes, Healy & Melville, 2018).  There are 627 traits included for each name, based on a list generated by Peabody (1987; Charlesworth, et al., 2021). Estimates of trait valence are from human judgments, estimated on a 9-pt Likert scale ranging from unhappy (1) to happy (9; Warriner, Kuperman, & Brysbaert, 2013)."),
                      br(),
                      br(),
                      h4("References:"),
                      helpText("Bojanowski, P., Grave, E., Joulin, A., & Mikolov, T. (2016). Enriching word vectors with subword information. https://arxiv.org/abs/1607.04606"),
                      helpText("Charlesworth, T. E. S., *Yang, V., Mann, T. C., Kurdi, B., & Banaji, M. R. (2021). Gender stereotypes in natural language: Word embeddings show robust consistency across child and adult language corpora of 65+ million words. Psychological Science."),
                      helpText("McInnes, L., Healy, H., and Melville, J. (2018). Umap: Uniform manifold approximation and projection for dimension reduction. arXiv preprint arXiv:1802.03426 ."),
                      helpText("Peabody, D. (1987). Selecting representative trait adjectives.  Journal of Personality and Social Psychology, 52, 59–71. doi:10.1037/0022-3514.52.1.59"),
                      helpText("Warriner, A. B., Kuperman, V., & Brysbaert, M. (2013). Norms of valence, arousal, and dominance for 13,915 English lemmas. Behavior Research Methods, 45(4), 1191-1207."),
                      helpText("Wickham, H. (2019). babynames: US Baby Names1880-2017. R package version 1.0.0. https://CRAN.R-project.org/package=babynames"),
                      br(),
                      h4("Creator: Molly Lewis"),
                      HTML("<i class='fa fa-envelope'></i> <a href='mailto:mollyllewis@gmail.com'> mollyllewis@gmail.com</a>"),
                      br(),
                      HTML("<i class='fa fa-globe'></i><a href='http://www.andrew.cmu.edu/user/mollylew/'> Website</a>"),
                      br(),
                      HTML("<i class='fa fa-twitter'></i> @mollyllewis"),
                      br(),
                      HTML("<i class='fa fa-github'></i> @mllewis"),
                      br(),
                      br(),
                      h4("Source code availabel here:"),
                      
                      
                      
                      
                      
                      
                      
                      )
            )
      )
    )
)
)
